services:
  app:
    container_name: vaccine-app
    hostname: app
    build:
      context: .
    volumes:
      - .:/usr/src/app/
    networks:
      - proxy-dvwa-web

networks:
  proxy-dvwa-web:
    name: dvwa_web
    external: true
