services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
    hostname: server
    volumes:
      - ./app:/usr/src/app/
    networks:
      - main
  source:
    container_name: src
    build:
      context: .
      dockerfile: Dockerfile.src
    hostname: src
    networks:
      - main
  destination:
    container_name: dest
    build:
      context: .
      dockerfile: Dockerfile.dest
    hostname: dest
    networks:
      - main

networks:
  main: