FROM debian:bookworm

ARG USER=ftpuser
ARG PASS=ftpuser

RUN apt-get update -y && apt-get install -y \
    iputils-ping \
    net-tools \
    curl \
    vsftpd 

RUN useradd ${USER} \
    -g users \
    -G sudo \
    -m \
    -p $(openssl passwd -6 "${PASS}")

RUN  mkdir -p /etc/vsftpd/ && \
    mkdir -p /var/run/vsftpd/empty
COPY confs/vsftpd.conf /etc/vsftpd/vsftpd.conf

CMD ["vsftpd", "/etc/vsftpd/vsftpd.conf"]
HEALTHCHECK CMD netstat -lnt | grep :21 || exit 1