services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
    hostname: 'server'
    volumes:
      - ./app:/urs/srcs/app/
  source:
    container_name: src
    build:
      context: .
      dockerfile: Dockerfile.client
    hostname: src
  destination:
    container_name: dest
    build:
      context: .
      dockerfile: Dockerfile.client
    hostname: dest