services:
  app:
    container_name: vaccine-app
    hostname: app
    build:
      context: app
    volumes:
      - ./app:/usr/src/app/
    networks:
      - app
  dvwa:
    container_name: vaccine-dvwa
    hostname: dvwa
    build:
      context: dvwa
    volumes:
      - ./dvwa:/app
    networks:
      - app
    ports:
      - 8000:8000
  mysql:
    image: mysql:8.0
    container_name: vaccine-mysql
    hostname: mysql
    networks:
      - app
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vaccine
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
networks:
  app: